source_lang: "hi"
target_lang: "en"
#reset_lr_scheduler: True
arch: "transformer"
encoder_layers: 6
decoder_layers: 6
encoder_attention_heads: 8
decoder_attention_heads: 8
encoder_embed_dim: 512
decoder_embed_dim: 512
encoder_ffn_embed_dim: 2048
decoder_ffn_embed_dim: 2048
encoder_normalize_before: True
decoder_normalize_before: True
dropout: 0.2
attention_dropout: 0.2
relu_dropout: 0.2
weight_decay: 0.00001
label_smoothing: 0.2
criterion: "label_smoothed_cross_entropy"
optimizer: "adam"
adam_betas: '(0.9, 0.98)'
clip_norm: 0.5
lr_scheduler: "inverse_sqrt"
lr: 0.01
min_lr: 1e-9
max_tokens: 3500
warmup_updates: 8000
warmup_init_lr: 1e-7
update_freq: 4
save_interval: 10
max_epoch: 200
